### ISSUE TITLE
Not able to install Taylor framework from Rome- What i am doing wrong ?

### ISSUE THREAD

**Issue by karthikprabhuA** [izqui/Taylor#10]
Installing Taylor framework fails and giving the following error "fatal: repository 'https://github.com/nypisces/Taylor.git/' not found"
It seems that taylor github path is wrong...

 PodFile
---Start----
platform :osx, '10.9'
platform :ios, '8.0'
plugin 'cocoapods-rome'

pod 'Taylor'

--End--

pod install
Updating local specs repositories

CocoaPods 0.39.0.beta.4 is available.
To update use: gem install cocoapods --pre
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Downloading dependencies
Installing AFNetworking (1.3.4)
Installing ISO8601DateFormatterValueTransformer (0.6.1)
Installing RKValueTransformers (1.1.2)
Installing RestKit (0.25.0)
Installing SOCKit (1.1)
Installing Taylor (0.1.0)

[!] Error installing Taylor
[!] /usr/bin/git clone https://github.com/nypisces/Taylor.git /var/folders/zx/xkz4mnmj58s52gct0mc2hzbh0000gn/T/d20150909-18579-g54bgr --single-branch --depth 1 --branch 0.1.0

Cloning into '/var/folders/zx/xkz4mnmj58s52gct0mc2hzbh0000gn/T/d20150909-18579-g54bgr'...
remote: Repository not found.
fatal: repository 'https://github.com/nypisces/Taylor.git/' not found

**Comment by Danappelxx** [comment]
Unfortunately it's pretty difficult to use Taylor right now - the only way that _sometimes_ works for me is by changing `pod 'Taylor'` to `pod 'Taylor', :git => 'https://github.com/izqui/taylor_test'`. Hopefully this will change once izqui finally merges the two repositories and tags a new release.

Also to why it's linking to nypisces/Taylor.git, I have no idea - that really strange. Perhaps he forked and did a `pod trunk push` (overwriting Taylor) but then took down his repo?

**Comment by izqui** [comment]
Hi @Danappelxx, sorry for the trouble. 

I just got it to build using the following Podfile:

```
platform :osx, '10.10'

plugin 'cocoapods-rome'

pod 'Taylor', :git => 'https://github.com/izqui/taylor_test.git'
```

I will do the merge with izqui/Taylor really soon and request the pod name Taylor as soon as I finish debugging one last bug.

**Comment by karthikprabhuA** [comment]
Thanks @Danappelxx  and @izqui .
@izqui Notify once done , its really a great work . Would be better if you provide a detailed steps to execute the script from command line

**Comment by Danappelxx** [comment]
@izqui the setup worked and it builds & runs successfully, so that's great! The server itself isn't working for me, however (though I assume this is one of those bugs you said you were fixing). 

![](http://puu.sh/k71m1/12c63da834.png)

**Comment by izqui** [comment]
Solved now! Check new README
