### ISSUE TITLE
[TODO] Cocoapods 0.3.0 release. Swift Sockets dependency

### ISSUE THREAD

**Issue by izqui** [izqui/Taylor#17]
I was preparing the 0.3.0 release when I realized that https://github.com/AlwaysRightInstitute/SwiftSockets isn't in CocoaPods.

**Comment by Danappelxx** [comment]
He has an issue that's an entire year old about whether to add cocoapods support. Maybe revive it? https://github.com/AlwaysRightInstitute/SwiftSockets/issues/5

**Comment by izqui** [comment]
Waiting on this PR to be merged: https://github.com/AlwaysRightInstitute/SwiftSockets/pull/11

Also, looks like I broke Mac support when releasing 2.1, will have to do a full check as soon as the SwiftSockets dependency is ready.

**Comment by izqui** [comment]
Up and running
