### ISSUE TITLE
can not run in Xcode 7

### ISSUE THREAD

**Issue by jiuxuanzhi** [izqui/Taylor#23]
I am new in swift, i cloned this project and import into my Xcode, but it can not run, there are two erros shown, any tips can you help me, thanks advance.

<img width="1015" alt="7b03adc2-e79c-43f2-b020-55a738f0a556" src="https://cloud.githubusercontent.com/assets/2564493/10911583/7a22d242-8280-11e5-973a-d1e4f3dcf275.png">

**Comment by izqui** [comment]
Hi!

You need to run `carthage bootstrap` in the console to fetch the dependency, in case you want to develop the library.

In case you are starting with Swift and just want to have a look, I would advise you to follow the Playground instructions and play with it there. https://github.com/izqui/Taylor#playground

**Comment by jiuxuanzhi** [comment]
Thank you very much, i did as your instruction, yeah, i have installed carthage tool on my Mac before and it works!
