### ISSUE TITLE
[Suggestion] Make a Slack/Gitter/whatever

### ISSUE THREAD

**Issue by Danappelxx** [izqui/Taylor#25]
This would make asking silly questions easier since one would be asking in a more relaxed environment. It's also neat for discussion where you don't want to create a Github issue to reach out to the community.

**Comment by levin-ilya** [comment]
+1 for Slack

**Comment by izqui** [comment]
That's a great idea.

I just created a Slack. I'm working on a way to let people autoinvite themselves (might be doing something like this https://levels.io/slack-typeform-auto-invite-sign-ups/)

If someone wants to enter before that system is ready, just leave a comment with your email address.

**Comment by izqui** [comment]
Testing slack integration

**Comment by izqui** [comment]
Okay, @alexperezpaya is on it.

**Comment by izqui** [comment]
Okey, we are live.

Sign up in http://taylor-framework.herokuapp.com to join the Taylor Slack group.

**Comment by jpbernius** [comment]
this web-page will print a paid_teams_only error message. (Error 400 in Console)

**Comment by perezpaya** [comment]
That might be working now. @jpbernius
